version: '3.8'
services:
  dynamodb:
    container_name: ts-graphql-dynamodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8111:8000"
    volumes:
      - dynamodb-ts-graphql-local:/home/dynamodblocal/db
volumes:
  dynamodb-ts-graphql-local:
    driver: local
