- Effect: Allow
  Action:
    - ssm:Describe*
    - ssm:Get*
  Resource: arn:aws:ssm:ap-southeast-2:${self:custom.account}:parameter/*

- Effect: Allow
  Action:
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.stage}_movies"
