MovieTable:
  Type: 'AWS::DynamoDB::Table'
  Properties:
    AttributeDefinitions:
      - AttributeName: Year
        AttributeType: N
      - AttributeName: Title
        AttributeType: S
    KeySchema:
      - AttributeName: Year
        KeyType: HASH
      - AttributeName: Title
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    # This is not required because we set BillingMode to Provisioned
    # To make dynamodb on demand, all we need to do is to remove ProvisionedThrougput
    # and add BillingMode
    # ProvisionedThroughput:
    #   ReadCapacityUnits: 1
    #   WriteCapacityUnits: 1
    TableName: ${self:custom.env}_movies
