MovieTable:
  Type: 'AWS::DynamoDB::Table'
  Properties:
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: year
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: year
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    # This is not required because we set BillingMode to Provisioned
    # To make dynamodb on demand, all we need to do is to remove ProvisionedThrougput
    # and add BillingMode
    # ProvisionedThroughput:
    #   ReadCapacityUnits: 1
    #   WriteCapacityUnits: 1
    TableName: ${self:custom.env}_movies
    GlobalSecondaryIndexes:
      - IndexName: movieTitleIndex
        KeySchema:
          - AttributeName: title
            KeyType: HASH
        Projection:
          ProjectionType: ALL
