import { embed } from '@aws/dynamodb-data-mapper';
import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';
import { Field, ID, ObjectType } from 'type-graphql';
import { Cast } from './Cast';
import { Quote } from './Quote';

const tableName = 'movies';

@table(tableName)
@ObjectType()
export class Movie {
  @autoGeneratedHashKey()
  @Field(_type => ID)
  id: string;

  @rangeKey()
  @Field()
  title: string;

  @attribute()
  @Field()
  year: number;

  @attribute()
  @Field()
  country: string;

  @attribute()
  @Field()
  director: string;

  @attribute()
  @Field(_type => [String])
  genra: string[];

  @attribute({memberType: embed(Cast)})
  @Field(_type => [Cast])
  cast: Cast[];

  @attribute()
  @Field()
  description: string;

  @attribute()
  @Field()
  whyShouldWeWatch: string;

  @attribute({memberType: embed(Quote)})
  @Field(_type => [Quote])
  quotes: Quote[];

  @attribute()
  @Field()
  language: string;
}
